/** Auto-generated icon name lists for ab-elements-demo — do not hand-edit. */
export const MATERIAL_ICON_NAMES = ["home", "search", "settings", "favorite", "shopping_bag", "person", "menu", "close", "check", "add", "edit", "delete", "arrow_back", "arrow_forward", "chevron_left", "chevron_right", "expand_more", "expand_less", "more_vert", "more_horiz", "info", "warning", "error", "help", "check_circle", "cancel", "schedule", "today", "event", "notifications", "mail", "send", "phone", "chat", "videocam", "photo_camera", "image", "folder", "description", "download", "upload", "cloud", "link", "share", "visibility", "visibility_off", "lock", "lock_open", "key", "login", "logout", "account_circle", "group", "public", "place", "map", "navigation", "local_shipping", "store", "payments", "credit_card", "shopping_cart", "star", "thumb_up", "thumb_down", "bookmark", "flag", "print", "content_copy", "content_paste", "undo", "redo", "refresh", "sync", "filter_list", "sort", "tune", "dashboard", "apps", "widgets", "code", "terminal", "bug_report", "build", "handyman", "light_mode", "dark_mode", "palette"] as const;

export const ANT_ICON_NAMES = {
  filled: ["bell", "check", "close", "edit", "heart", "home", "mail", "plus", "search", "setting", "star", "user"],
  outlined: ["bell", "check", "close", "edit", "heart", "home", "mail", "plus", "search", "setting", "star", "user"],
} as const;

/** AbIcons — Material snake_case set (`abicons/`). */
export const AB_ICON_NAMES = {
  filled: ["account_circle", "analytics", "bookmark", "bug_report", "build", "calendar_today", "camera", "cancel", "chat", "check_box", "check_circle", "cloud", "content_copy", "dark_mode", "dashboard", "delete", "edit", "error", "favorite", "folder", "help", "home", "image", "info", "light_mode", "location_on", "lock", "lock_open", "mail", "map", "mic", "more_horiz", "more_vert", "notifications", "palette", "pause", "payments", "person", "phone", "play_arrow", "print", "radio_button_checked", "save", "schedule", "send", "settings", "share", "shopping_cart", "star", "terminal", "tune", "visibility", "volume_up", "warning", "widgets"],
  outlined: ["account_circle", "add", "analytics", "arrow_back", "arrow_forward", "attach_file", "bookmark", "bug_report", "build", "calendar_today", "camera", "cancel", "chat", "check", "check_box", "check_box_outline_blank", "check_circle", "chevron_left", "chevron_right", "close", "cloud", "code", "content_copy", "dark_mode", "dashboard", "delete", "done", "download", "edit", "error", "expand_less", "expand_more", "favorite", "filter_list", "folder", "help", "home", "image", "info", "language", "light_mode", "link", "location_on", "lock", "lock_open", "login", "logout", "mail", "map", "menu", "mic", "more_horiz", "more_vert", "notifications", "open_in_new", "palette", "pause", "payments", "person", "phone", "play_arrow", "print", "radio_button_checked", "radio_button_unchecked", "redo", "refresh", "save", "schedule", "search", "send", "settings", "share", "shopping_cart", "sort", "star", "terminal", "tune", "undo", "upload", "visibility", "visibility_off", "volume_up", "warning", "widgets"],
} as const;
